modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="fastfurnace" #mandatory

version="${file.jarVersion}" #mandatory

displayName="FastFurnace" #mandatory

description='''
Furnace improvements. Covers all "furnace-based" vanilla blocks.
'''

[[dependencies.fastfurnace]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34.1,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.fastfurnace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fastfurnace]]
    modId="placebo"
    mandatory=true
    versionRange="[4.3,)"
    ordering="NONE"
    side="BOTH"
